language: python
python:
  - "3.6"
before_install:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - pip install -r requirements.txt
script:
  - python3 ./tests/player_tests.py
  - python3 ./tests/ball_tests.py
  - python3 ./tests/node_tests.py
  - python3 ./tests/tournament_tests.py
  - python3 ./tests/server_tests.py
